### ISSUE TITLE
why is `event.persist()` here?

### ISSUE THREAD

**Issue by geluso** [learn-co-curriculum/react-async-readme#5]
What purpose does `event.persist()` serve here?

https://github.com/learn-co-curriculum/react-async-readme/blame/master/README.md#L144

**Comment by maxwellbenton** [comment]
That is a great question, @geluso. I think it was vestigial from somewhere else. I vaguely remember there being something about the callback version of `setState` sometimes requiring an event to persist, but that doesn't apply here, so I've removed it.

Thank you for catching this!
